GGW/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GGW.Models;


namespace GGW.Controllers
{
    public class AdminController : Controller
    {
        GGWdbContext db = new GGWdbContext();
        // GET: Admin
        public ActionResult Index()
        {
            var rr = db.adminM.Select(e => e);
            return View(rr);
        }
        public ActionResult insert(string username, string userpwd,adminM MM)
        {
            if (username != null && userpwd != null)
            {
                var name_re = db.adminM.Where(e => e.adminName == username);
                if (name_re.ToList().Count > 0)
                {
                    return Json(new { s = "00" });
                }
                var re = db.adminM.Where(e => e.adminName == username && e.adminPwd == userpwd);
                if (re.ToList().Count > 0)
                {
                    return Json(new { s = "1" });
                }
                else
                {
                    MM.adminName = username.ToString();
                    MM.adminPwd = userpwd.ToString();
                    db.adminM.Add(MM);
                    db.SaveChanges();
                    return Json(new { s = "ok" });
                }
            }
            else
            {
                return Json(new { s = "0" });

            }

        }

        public ActionResult Sel_news()
        {
            var re = db.news.Select(e => e);
            return View(re);
        }
        public ActionResult Edit_news()
        {
            var re = db.news.Select(e=>e);
            return View(re);
        }
        public ActionResult Edit(int id)
        {
            var re = db.news.Find(id);
            return View(re);
        }
        [HttpPost]
        public ActionResult Edit(news nn)
        {
            var re = db.news.Find(nn.id);
            UpdateModel(re);
            db.SaveChanges();
            return RedirectToAction("Edit_news");
        }
        public ActionResult Delete(int id)
        {
            var re = db.news.Find(id);
            db.news.Remove(re);
            db.SaveChanges();
            return RedirectToAction("Edit_news");
        }
        public ActionResult up_news()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult up_news(news nn)
        {
            if (ModelState.IsValid)
            {
                db.news.Add(nn);
                db.SaveChanges();
                return RedirectToAction("Sel_news");

            }
            else
                return View();
        }
    }
}

GGW/Controllers/JoinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GGW.Controllers
{
    public class JoinController : Controller
    {
        // GET: Join
        public ActionResult Index()
        {
            ViewBag.title = "招商加盟";
            return View();
        }
    }
}

GGW/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GGW.Controllers
{
    public class MyController : Controller
    {
        // GET: My
        public ActionResult Index()
        {
            ViewBag.title = "关于我们";
            return View();
        }
        public ActionResult introduce()
        {
            ViewBag.title = "公司介绍";
            return View();
        }
        public ActionResult culture()
        {
            ViewBag.title = "企业文化";
            return View();
        }
    }
}

GGW/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GGW.Models;

namespace GGW.Controllers
{
    public class NewsController : Controller
    {
        GGWdbContext db = new GGWdbContext();
        // GET: News
        public ActionResult Index()
        {
            ViewBag.title = "新闻中心";
            var c = db.news.Select(e => e);
            return View(c);
        }
    }
}

GGW/Views/Shared/F.cshtml
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.0.0.min.js"></script>

<style>
    .col-6{
        color:#fff;
        padding-top:20px;
    }
    .col-6 h3 {
       padding-top:25px;
       padding-left:80px;
    }
        .col-6 p {
            padding-left: 80px;
        }
        .TB{
            padding-top:50px;
            padding-left:40px
        }
</style>

<div class="container-fluid" style="background-color: #808080;height:300px;padding-top:20px;">
    <div class="row">
        <div class="col-6">
            <h3>某省某市包满意服务有限公司</h3>
            <p>电话：0760-22517081 传真：0760-86744123</p>
            <p>Email：service</p>
            <p>地址：某省某市中心广场王府井B座16号</p>
            <p>© 2019 版权所有</p>
        </div>
        <div class="col-6 TB">
            <img src="~/image/erweima.png" style="width:200px;height:200px;" />
        </div>
    </div>
</div>

GGW/Views/Shared/H.cshtml
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-3.0.0.min.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
<style>

    .col-4 {
        text-align: center;
    }

    .titl ul {
        list-style: none;
    }

        .titl ul li {
            height:40px;
            text-align:center;
            width:70px;
            float: left;
            margin-left: 50px;
            margin-top: 50px;
        }

    .titl a {
        color: #b0afaf;
    }

        .titl a:hover {
            color: #000000;
            text-decoration: none;
        }

    #box-ul {
        width: 120px;
        height: 50px;
        border: 1px solid red;
        position: relative;
        margin: -50px auto 0px auto
    }

        #box-ul ul li {
            float: left;
            color: #fff;
        }
    .show-hr {
        border: 1.5px solid #999;
        border-radius: 1.5px;
        display: none;
        margin-top: 5px;
        position: relative;
        width: 0px;
        
    }
</style>

<div class="container-fluid">
    <div class="row">
        <div class="col-4">
            <a href="#">
                <img src="~/image/logo.png" alt="Alternate Text" />
            </a>
        </div>
        <div class="col-8 titl">
            <ul>
                <li>
                    @Html.ActionLink("首页", "Index", "Home")<hr class="show-hr"/>
                            </li>
                <li>@Html.ActionLink("关于我们", "Index", "My")<hr class="show-hr" /></li>
                <li>@Html.ActionLink("新闻中心", "Index", "News")<hr class="show-hr" /></li>
                <li>@Html.ActionLink("招商加盟", "Index", "Join")<hr class="show-hr" /></li>
                <li>@Html.ActionLink("工程案例", "Index", "Case")<hr class="show-hr" /></li>
                <li>@Html.ActionLink("联系我们", "Index", "Contact")<hr class="show-hr" /></li>
            </ul>
        </div>
    </div>
</div>
<div class="container-fluid">
</div>
<script>
    $(function () {
        $('.titl ul li').hover(function () {
            var c = $(this).index();
            $('.show-hr').eq(c).css({ 'display': 'block', 'width': '70px', 'transition': '2s','opacity':'0.5', })
        }, function () { $('.show-hr').css('display', 'none') })
    })
</script>

GGW/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<meta name="description" content="Ela Admin - HTML5 Admin Template">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="~/assets/css/normalize.css" rel="stylesheet" />
<link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
<link rel="stylesheet" href="~/assets/css/themify-icons.css">
<link rel="stylesheet" href="~/assets/css/pe-icon-7-filled.css">
<link rel="stylesheet" href="~/assets/css/flag-icon.min.css"><link rel="stylesheet" href="assets/css/cs-skin-elastic.css">
<link rel="stylesheet" href="~/assets/css/style.css">
<link href="~/assets/weather/css/weather-icons.css" rel="stylesheet" />
<link href="~/assets/calendar/fullcalendar.css" rel="stylesheet" />

<link href="~/assets/css/charts/chartist.min.css" rel="stylesheet">
<link href="~/assets/css/lib/vector-map/jqvmap.min.css" rel="stylesheet">
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div style="position:relative">
        @Html.Partial("~/Views/Shared/adminF.cshtml")
    </div>
    <div>
        @Html.Partial("~/Views/Shared/adminH.cshtml")
    </div>
    <div class="pull-right" style="width:75%;">
        @RenderBody()
    </div>
</body>
</html>

GGW/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.0.0.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
</head>
<body>
    <div>
        @Html.Partial("~/Views/Shared/H.cshtml")
    </div>
    <div>
        @RenderBody()
    </div>
    <div>
        @Html.Partial("~/Views/Shared/F.cshtml")
    </div>
</body>
</html>

GGW/Views/Shared/adminF.cshtml
<meta name="description" content="Ela Admin - HTML5 Admin Template">
<meta name="viewport" content="width=device-width, initial-scale=1">



<link href="~/assets/css/normalize.css" rel="stylesheet" />
<link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
<link rel="stylesheet" href="~/assets/css/themify-icons.css">
<link rel="stylesheet" href="~/assets/css/pe-icon-7-filled.css">
<link rel="stylesheet" href="~/assets/css/flag-icon.min.css"><link rel="stylesheet" href="assets/css/cs-skin-elastic.css">
<link rel="stylesheet" href="~/assets/css/style.css">
<link href="~/assets/weather/css/weather-icons.css" rel="stylesheet" />
<link href="~/assets/calendar/fullcalendar.css" rel="stylesheet" />

<link href="~/assets/css/charts/chartist.min.css" rel="stylesheet">
<link href="~/assets/css/lib/vector-map/jqvmap.min.css" rel="stylesheet">

<style>
    #weatherWidget .currentDesc {
        color: #ffffff !important;
    }

    .traffic-chart {
        min-height: 335px;
    }

    #flotPie1 {
        height: 150px;
    }

        #flotPie1 td {
            padding: 3px;
        }

        #flotPie1 table {
            top: 20px !important;
            right: -10px !important;
        }

    .chart-container {
        display: table;
        min-width: 270px;
        text-align: left;
        padding-top: 10px;
        padding-bottom: 10px;
    }

    #flotLine5 {
        height: 105px;
        
    }

    #flotBarChart {
        height: 150px;
    }

    #cellPaiChart {
        height: 160px;
    }
</style>

<aside id="left-panel" class="left-panel">
    <nav class="navbar navbar-expand-sm navbar-default">
        <div id="main-menu" class="main-menu collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="index.html"><i class="menu-icon fa fa-laptop"></i>仪表盘 </a>
                </li>
                <li class="menu-title">用户管理</li><!-- /.menu-title -->
                <li class="menu-item-has-children dropdown">
                    <a href="@Url.Action("Index","Admin")"> 查看个人信息</a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="@Url.Action("Index","Admin_Edit")"> 编辑个人信息</a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="@Url.Action("Sel_user","Admin")"> 其他</a>
                </li>

                <li class="menu-title">新闻管理</li><!-- /.menu-title -->

                <li class="menu-item-has-children dropdown">
                    <a href="@Url.Action("Sel_news","Admin")"> 查看所有新闻</a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="@Url.Action("Edit_news","Admin")">编辑新闻</a>
                </li>
                <li class="menu-item-has-children dropdown">
                    <a href="@Url.Action("up_news","Admin")">上传新闻</a>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</aside>

GGW/Views/Shared/adminH.cshtml
<meta name="description" content="Ela Admin - HTML5 Admin Template">
<meta name="viewport" content="width=device-width, initial-scale=1">



<link href="~/assets/css/normalize.css" rel="stylesheet" />
<link rel="stylesheet" href="~/assets/css/bootstrap.min.css">
<link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
<link rel="stylesheet" href="~/assets/css/themify-icons.css">
<link rel="stylesheet" href="~/assets/css/pe-icon-7-filled.css">
<link rel="stylesheet" href="~/assets/css/flag-icon.min.css"><link rel="stylesheet" href="assets/css/cs-skin-elastic.css">
<link rel="stylesheet" href="~/assets/css/style.css">
<link href="~/assets/weather/css/weather-icons.css" rel="stylesheet" />
<link href="~/assets/calendar/fullcalendar.css" rel="stylesheet" />

<link href="~/assets/css/charts/chartist.min.css" rel="stylesheet">
<link href="~/assets/css/lib/vector-map/jqvmap.min.css" rel="stylesheet">

<style>
    #weatherWidget .currentDesc {
        color: #ffffff !important;
    }

    .traffic-chart {
        min-height: 335px;
    }

    #flotPie1 {
        height: 150px;
    }

        #flotPie1 td {
            padding: 3px;
        }

        #flotPie1 table {
            top: 20px !important;
            right: -10px !important;
        }

    .chart-container {
        display: table;
        min-width: 270px;
        text-align: left;
        padding-top: 10px;
        padding-bottom: 10px;
    }

    #flotLine5 {
        height: 105px;
    }

    #flotBarChart {
        height: 150px;
    }

    #cellPaiChart {
        height: 160px;
    }
</style>
<div id="right-panel" class="right-panel">
    <!-- Header-->
    <header id="header" class="header">
        <div class="top-left">
            <div class="navbar-header">
                <a class="navbar-brand" href="./"><img src="~/image/logo1.png" alt="Logo"></a>
                <a class="navbar-brand hidden" href="./"><img src="~/image/logo2.png" alt="Logo"></a>
                <a id="menuToggle" class="menutoggle"><i class="fa fa-bars"></i></a>
            </div>
        </div>
        <div class="top-right">
            <div class="header-menu">
                <div class="header-left">
                    <button class="search-trigger"><i class="fa fa-search"></i></button>
                    <div class="form-inline">
                        <form class="search-form">
                            <input class="form-control mr-sm-2" type="text" placeholder="Search ..." aria-label="Search">
                            <button class="search-close" type="submit"><i class="fa fa-close"></i></button>
                        </form>
                    </div>

                    <div class="dropdown for-notification">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="notification" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-bell"></i>
                            <span class="count bg-danger">3</span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="notification">
                            <p class="red">You have 3 Notification</p>
                            <a class="dropdown-item media" href="#">
                                <i class="fa fa-check"></i>
                                <p>Server #1 overloaded.</p>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <i class="fa fa-info"></i>
                                <p>Server #2 overloaded.</p>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <i class="fa fa-warning"></i>
                                <p>Server #3 overloaded.</p>
                            </a>
                        </div>
                    </div>

                    <div class="dropdown for-message">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="message" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-envelope"></i>
                            <span class="count bg-primary">4</span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="message">
                            <p class="red">You have 4 Mails</p>
                            <a class="dropdown-item media" href="#">
                                <span class="photo media-left"><img alt="avatar" src="~/image/avatar/1.jpg"></span>
                                <div class="message media-body">
                                    <span class="name float-left">Jonathan Smith</span>
                                    <span class="time float-right">Just now</span>
                                    <p>Hello, this is an example msg</p>
                                </div>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <span class="photo media-left"><img alt="avatar" src="~/image/avatar/2.jpg"></span>
                                <div class="message media-body">
                                    <span class="name float-left">Jack Sanders</span>
                                    <span class="time float-right">5 minutes ago</span>
                                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                                </div>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <span class="photo media-left"><img alt="avatar" src="~/image/avatar/3.jpg"></span>
                                <div class="message media-body">
                                    <span class="name float-left">Cheryl Wheeler</span>
                                    <span class="time float-right">10 minutes ago</span>
                                    <p>Hello, this is an example msg</p>
                                </div>
                            </a>
                            <a class="dropdown-item media" href="#">
                                <span class="photo media-left"><img alt="avatar" src="~/image/avatar/4.jpg"></span>
                                <div class="message media-body">
                                    <span class="name float-left">Rachel Santos</span>
                                    <span class="time float-right">15 minutes ago</span>
                                    <p>Lorem ipsum dolor sit amet, consectetur</p>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>

                <div class="user-area dropdown float-right">
                    <a href="#" class="dropdown-toggle active" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img class="user-avatar rounded-circle" src="~/image/admin.jpg" alt="User Avatar">
                    </a>
                    <div class="user-menu dropdown-menu">
                        <a class="nav-link" href="#"><i class="fa fa- user"></i>My Profile</a>

                        <a class="nav-link" href="#"><i class="fa fa- user"></i>Notifications <span class="count">13</span></a>

                        <a class="nav-link" href="#"><i class="fa fa -cog"></i>Settings</a>

                        <a class="nav-link" href="#"><i class="fa fa-power -off"></i>Logout</a>
                    </div>
                </div>

            </div>
        </div>
    </header>
</div>